-- 코드를 입력하세요
SELECT TITLE, gb.BOARD_ID, REPLY_ID, gr.WRITER_ID, gr.CONTENTS, DATE_FORMAT(gr.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as gb
INNER JOIN USED_GOODS_REPLY as gr
ON gb.BOARD_ID = gr.BOARD_ID
WHERE YEAR(gb.CREATED_DATE) = 2022
AND MONTH(gb.CREATED_DATE) = 10
ORDER BY gr.CREATED_DATE, gb.TITLE;